use super::{Language, localized_text, reward_roll_key};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum CardId {
    FlareSlash,
    FlareSlashPlus,
    GuardStep,
    GuardStepPlus,
    Slipstream,
    SlipstreamPlus,
    QuickStrike,
    QuickStrikePlus,
    Reinforce,
    ReinforcePlus,
    PressurePoint,
    PressurePointPlus,
    SunderingArc,
    SunderingArcPlus,
    TwinStrike,
    TwinStrikePlus,
    BarrierField,
    BarrierFieldPlus,
    TacticalBurst,
    TacticalBurstPlus,
    RazorNet,
    RazorNetPlus,
    BreachSignal,
    BreachSignalPlus,
    AnchorLoop,
    AnchorLoopPlus,
    ExecutionBeam,
    ExecutionBeamPlus,
    FortressMatrix,
    FortressMatrixPlus,
    ZeroPoint,
    ZeroPointPlus,
    PinpointJab,
    PinpointJabPlus,
    SignalTap,
    SignalTapPlus,
    BurstArray,
    BurstArrayPlus,
    CoverPulse,
    CoverPulsePlus,
    FracturePulse,
    FracturePulsePlus,
    VectorLock,
    VectorLockPlus,
    ChainBarrage,
    ChainBarragePlus,
    OverwatchGrid,
    OverwatchGridPlus,
    RiftDart,
    RiftDartPlus,
    MarkPulse,
    MarkPulsePlus,
    BraceCircuit,
    BraceCircuitPlus,
    FaultShot,
    FaultShotPlus,
    SeverArc,
    SeverArcPlus,
    Lockbreaker,
    LockbreakerPlus,
    CounterLattice,
    CounterLatticePlus,
    TerminalLoop,
    TerminalLoopPlus,
    ArcSpark,
    ArcSparkPlus,
    CapacitiveShell,
    CapacitiveShellPlus,
    PrimeRoutine,
    PrimeRoutinePlus,
    Stockpile,
    StockpilePlus,
    PulseConverter,
    PulseConverterPlus,
    ReservoirGuard,
    ReservoirGuardPlus,
    VoltaicDrive,
    VoltaicDrivePlus,
    StormVault,
    StormVaultPlus,
    SparkSmith,
    SparkSmithPlus,
    PatchBay,
    PatchBayPlus,
    TracerWeave,
    TracerWeavePlus,
    NeedleNest,
    NeedleNestPlus,
    AssemblyLine,
    AssemblyLinePlus,
    ToolCache,
    ToolCachePlus,
    ImprovisedArsenal,
    ImprovisedArsenalPlus,
    ForgeStorm,
    ForgeStormPlus,
    SweepPulse,
    SweepPulsePlus,
    DimmingWave,
    DimmingWavePlus,
    ShrapnelVeil,
    ShrapnelVeilPlus,
    ScouringWind,
    ScouringWindPlus,
    CollapsePattern,
    CollapsePatternPlus,
    Linebreaker,
    LinebreakerPlus,
    NovaCollapse,
    NovaCollapsePlus,
    SuppressionNet,
    SuppressionNetPlus,
    RazorRush,
    RazorRushPlus,
    HardReset,
    HardResetPlus,
    EmergencyPlating,
    EmergencyPlatingPlus,
    Cauterize,
    CauterizePlus,
    EmberBurst,
    EmberBurstPlus,
    AshenVector,
    AshenVectorPlus,
    PurgeArray,
    PurgeArrayPlus,
    LastProtocol,
    LastProtocolPlus,
    Spark,
    Patch,
    Tracer,
    Needler,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum CardTarget {
    Enemy,
    SelfOnly,
    AllEnemies,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum AxisKind {
    Focus,
    Rhythm,
    Momentum,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum CardArchetype {
    Pressure,
    Bulwark,
    Momentum,
    Fabricate,
    Sweep,
    Burst,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct CardRequirement {
    pub(crate) axis: AxisKind,
    pub(crate) threshold: i8,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) struct CardTraits {
    pub(crate) temporary: bool,
    pub(crate) piercing: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct CardDef {
    pub(crate) id: CardId,
    pub(crate) name: &'static str,
    pub(crate) cost: u8,
    pub(crate) target: CardTarget,
    pub(crate) description: &'static str,
    pub(crate) archetype: CardArchetype,
    pub(crate) reward_tier: Option<RewardTier>,
    pub(crate) traits: CardTraits,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum RewardTier {
    Combat,
    Elite,
    Boss,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct ShopOffer {
    pub(crate) card: CardId,
    pub(crate) price: u32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct CardData {
    id: CardId,
    slug: &'static str,
    name_en: &'static str,
    name_es: &'static str,
    description_en: &'static str,
    description_es: &'static str,
    cost: u8,
    target: CardTarget,
    archetype: CardArchetype,
    reward_tier: Option<RewardTier>,
    elite_unlock_level: usize,
    traits: CardTraits,
    upgrade: Option<CardId>,
}

const fn traits(temporary: bool, piercing: bool) -> CardTraits {
    CardTraits {
        temporary,
        piercing,
    }
}

const BASE_CARD_CATALOG: &[CardId] = &[
    CardId::FlareSlash,
    CardId::GuardStep,
    CardId::Slipstream,
    CardId::QuickStrike,
    CardId::PinpointJab,
    CardId::SignalTap,
    CardId::Reinforce,
    CardId::PressurePoint,
    CardId::BurstArray,
    CardId::CoverPulse,
    CardId::SunderingArc,
    CardId::TwinStrike,
    CardId::BarrierField,
    CardId::TacticalBurst,
    CardId::RazorNet,
    CardId::FracturePulse,
    CardId::VectorLock,
    CardId::BreachSignal,
    CardId::AnchorLoop,
    CardId::ExecutionBeam,
    CardId::ChainBarrage,
    CardId::FortressMatrix,
    CardId::OverwatchGrid,
    CardId::ZeroPoint,
    CardId::RiftDart,
    CardId::MarkPulse,
    CardId::BraceCircuit,
    CardId::FaultShot,
    CardId::SeverArc,
    CardId::Lockbreaker,
    CardId::CounterLattice,
    CardId::TerminalLoop,
    CardId::ArcSpark,
    CardId::CapacitiveShell,
    CardId::PrimeRoutine,
    CardId::Stockpile,
    CardId::PulseConverter,
    CardId::ReservoirGuard,
    CardId::VoltaicDrive,
    CardId::StormVault,
    CardId::SparkSmith,
    CardId::PatchBay,
    CardId::TracerWeave,
    CardId::NeedleNest,
    CardId::AssemblyLine,
    CardId::ToolCache,
    CardId::ImprovisedArsenal,
    CardId::ForgeStorm,
    CardId::SweepPulse,
    CardId::DimmingWave,
    CardId::ShrapnelVeil,
    CardId::ScouringWind,
    CardId::CollapsePattern,
    CardId::Linebreaker,
    CardId::NovaCollapse,
    CardId::SuppressionNet,
    CardId::RazorRush,
    CardId::HardReset,
    CardId::EmergencyPlating,
    CardId::Cauterize,
    CardId::EmberBurst,
    CardId::AshenVector,
    CardId::PurgeArray,
    CardId::LastProtocol,
];

const KNOWN_CARD_CATALOG: &[CardId] = &[
    CardId::FlareSlash,
    CardId::FlareSlashPlus,
    CardId::GuardStep,
    CardId::GuardStepPlus,
    CardId::Slipstream,
    CardId::SlipstreamPlus,
    CardId::QuickStrike,
    CardId::QuickStrikePlus,
    CardId::Reinforce,
    CardId::ReinforcePlus,
    CardId::PressurePoint,
    CardId::PressurePointPlus,
    CardId::SunderingArc,
    CardId::SunderingArcPlus,
    CardId::TwinStrike,
    CardId::TwinStrikePlus,
    CardId::BarrierField,
    CardId::BarrierFieldPlus,
    CardId::TacticalBurst,
    CardId::TacticalBurstPlus,
    CardId::RazorNet,
    CardId::RazorNetPlus,
    CardId::BreachSignal,
    CardId::BreachSignalPlus,
    CardId::AnchorLoop,
    CardId::AnchorLoopPlus,
    CardId::ExecutionBeam,
    CardId::ExecutionBeamPlus,
    CardId::FortressMatrix,
    CardId::FortressMatrixPlus,
    CardId::ZeroPoint,
    CardId::ZeroPointPlus,
    CardId::PinpointJab,
    CardId::PinpointJabPlus,
    CardId::SignalTap,
    CardId::SignalTapPlus,
    CardId::BurstArray,
    CardId::BurstArrayPlus,
    CardId::CoverPulse,
    CardId::CoverPulsePlus,
    CardId::FracturePulse,
    CardId::FracturePulsePlus,
    CardId::VectorLock,
    CardId::VectorLockPlus,
    CardId::ChainBarrage,
    CardId::ChainBarragePlus,
    CardId::OverwatchGrid,
    CardId::OverwatchGridPlus,
    CardId::RiftDart,
    CardId::RiftDartPlus,
    CardId::MarkPulse,
    CardId::MarkPulsePlus,
    CardId::BraceCircuit,
    CardId::BraceCircuitPlus,
    CardId::FaultShot,
    CardId::FaultShotPlus,
    CardId::SeverArc,
    CardId::SeverArcPlus,
    CardId::Lockbreaker,
    CardId::LockbreakerPlus,
    CardId::CounterLattice,
    CardId::CounterLatticePlus,
    CardId::TerminalLoop,
    CardId::TerminalLoopPlus,
    CardId::ArcSpark,
    CardId::ArcSparkPlus,
    CardId::CapacitiveShell,
    CardId::CapacitiveShellPlus,
    CardId::PrimeRoutine,
    CardId::PrimeRoutinePlus,
    CardId::Stockpile,
    CardId::StockpilePlus,
    CardId::PulseConverter,
    CardId::PulseConverterPlus,
    CardId::ReservoirGuard,
    CardId::ReservoirGuardPlus,
    CardId::VoltaicDrive,
    CardId::VoltaicDrivePlus,
    CardId::StormVault,
    CardId::StormVaultPlus,
    CardId::SparkSmith,
    CardId::SparkSmithPlus,
    CardId::PatchBay,
    CardId::PatchBayPlus,
    CardId::TracerWeave,
    CardId::TracerWeavePlus,
    CardId::NeedleNest,
    CardId::NeedleNestPlus,
    CardId::AssemblyLine,
    CardId::AssemblyLinePlus,
    CardId::ToolCache,
    CardId::ToolCachePlus,
    CardId::ImprovisedArsenal,
    CardId::ImprovisedArsenalPlus,
    CardId::ForgeStorm,
    CardId::ForgeStormPlus,
    CardId::SweepPulse,
    CardId::SweepPulsePlus,
    CardId::DimmingWave,
    CardId::DimmingWavePlus,
    CardId::ShrapnelVeil,
    CardId::ShrapnelVeilPlus,
    CardId::ScouringWind,
    CardId::ScouringWindPlus,
    CardId::CollapsePattern,
    CardId::CollapsePatternPlus,
    CardId::Linebreaker,
    CardId::LinebreakerPlus,
    CardId::NovaCollapse,
    CardId::NovaCollapsePlus,
    CardId::SuppressionNet,
    CardId::SuppressionNetPlus,
    CardId::RazorRush,
    CardId::RazorRushPlus,
    CardId::HardReset,
    CardId::HardResetPlus,
    CardId::EmergencyPlating,
    CardId::EmergencyPlatingPlus,
    CardId::Cauterize,
    CardId::CauterizePlus,
    CardId::EmberBurst,
    CardId::EmberBurstPlus,
    CardId::AshenVector,
    CardId::AshenVectorPlus,
    CardId::PurgeArray,
    CardId::PurgeArrayPlus,
    CardId::LastProtocol,
    CardId::LastProtocolPlus,
    CardId::Spark,
    CardId::Patch,
    CardId::Tracer,
    CardId::Needler,
];

pub(crate) fn card_def(id: CardId) -> CardDef {
    let data = card_data(id);
    CardDef {
        id: data.id,
        name: data.name_en,
        cost: data.cost,
        target: data.target,
        description: data.description_en,
        archetype: data.archetype,
        reward_tier: data.reward_tier,
        traits: data.traits,
    }
}

pub(crate) fn localized_card_def(id: CardId, language: Language) -> CardDef {
    let data = card_data(id);
    CardDef {
        id: data.id,
        name: localized_text(language, data.name_en, data.name_es),
        cost: data.cost,
        target: data.target,
        description: localized_text(language, data.description_en, data.description_es),
        archetype: data.archetype,
        reward_tier: data.reward_tier,
        traits: data.traits,
    }
}

pub(crate) fn localized_card_name(id: CardId, language: Language) -> &'static str {
    let data = card_data(id);
    localized_text(language, data.name_en, data.name_es)
}

pub(crate) fn upgraded_card(id: CardId) -> Option<CardId> {
    card_data(id).upgrade
}

pub(crate) fn card_requirement(id: CardId) -> Option<CardRequirement> {
    match id {
        CardId::PulseConverter | CardId::PulseConverterPlus => Some(CardRequirement {
            axis: AxisKind::Rhythm,
            threshold: 1,
        }),
        _ => None,
    }
}

pub(crate) fn all_base_cards() -> &'static [CardId] {
    BASE_CARD_CATALOG
}

pub(crate) fn starter_deck() -> Vec<CardId> {
    let mut cards = Vec::with_capacity(12);
    cards.extend(std::iter::repeat_n(CardId::FlareSlash, 5));
    cards.extend(std::iter::repeat_n(CardId::GuardStep, 4));
    cards.extend(std::iter::repeat_n(CardId::Slipstream, 2));
    cards.push(CardId::SunderingArc);
    cards
}

pub(crate) fn card_slug(id: CardId) -> &'static str {
    card_data(id).slug
}

pub(crate) fn resolve_card_slug(slug: &str) -> Option<CardId> {
    KNOWN_CARD_CATALOG
        .iter()
        .copied()
        .find(|card| card_data(*card).slug == slug)
}

pub(crate) fn reward_choices(seed: u64, tier: RewardTier, level: usize) -> Vec<CardId> {
    let mut cards = reward_pool(tier, level);
    cards.sort_by_key(|card| reward_roll_key(seed, *card));
    choose_distinct_archetypes(cards, 3)
}

pub(crate) fn shop_offers(seed: u64, level: usize) -> Vec<ShopOffer> {
    let mut chosen_cards = Vec::new();
    let mut chosen_archetypes = Vec::new();
    let mut offers = Vec::with_capacity(3);

    for (index, tier) in shop_offer_tiers(level).into_iter().enumerate() {
        let offer_seed = seed ^ (index as u64 + 1).wrapping_mul(0xD6E8_FD50_19E3_7C4B);
        let mut cards = reward_pool(tier, level);
        cards.sort_by_key(|card| reward_roll_key(offer_seed, *card));
        let card = cards
            .iter()
            .copied()
            .find(|card| {
                !chosen_cards.contains(card)
                    && !chosen_archetypes.contains(&card_def(*card).archetype)
            })
            .or_else(|| {
                cards
                    .iter()
                    .copied()
                    .find(|card| !chosen_cards.contains(card))
            })
            .or_else(|| cards.first().copied())
            .expect("shop tier should always have at least one card");
        chosen_archetypes.push(card_def(card).archetype);
        chosen_cards.push(card);
        offers.push(ShopOffer {
            card,
            price: shop_price_for_tier(tier),
        });
    }

    offers
}

fn choose_distinct_archetypes(cards: Vec<CardId>, limit: usize) -> Vec<CardId> {
    let mut chosen = Vec::with_capacity(limit);
    let mut archetypes = Vec::with_capacity(limit);

    for card in &cards {
        let archetype = card_def(*card).archetype;
        if !archetypes.contains(&archetype) {
            chosen.push(*card);
            archetypes.push(archetype);
            if chosen.len() == limit {
                return chosen;
            }
        }
    }

    for card in cards {
        if !chosen.contains(&card) {
            chosen.push(card);
            if chosen.len() == limit {
                break;
            }
        }
    }

    chosen
}

pub(crate) fn reward_pool(tier: RewardTier, level: usize) -> Vec<CardId> {
    let unlocked_level = level.clamp(1, 3);
    all_base_cards()
        .iter()
        .copied()
        .filter(|card| card_def(*card).reward_tier == Some(tier))
        .filter(|card| {
            if tier == RewardTier::Elite {
                card_data(*card).elite_unlock_level <= unlocked_level
            } else {
                true
            }
        })
        .collect()
}

fn shop_offer_tiers(level: usize) -> [RewardTier; 3] {
    match level.clamp(1, 3) {
        1 => [RewardTier::Combat, RewardTier::Elite, RewardTier::Elite],
        2 => [RewardTier::Combat, RewardTier::Elite, RewardTier::Boss],
        _ => [RewardTier::Elite, RewardTier::Elite, RewardTier::Boss],
    }
}

fn shop_price_for_tier(tier: RewardTier) -> u32 {
    match tier {
        RewardTier::Combat => 16,
        RewardTier::Elite => 24,
        RewardTier::Boss => 40,
    }
}

fn card_data(id: CardId) -> CardData {
    match id {
        CardId::FlareSlash => CardData {
            id,
            slug: "flare_slash",
            name_en: "Strike",
            name_es: "Golpe",
            description_en: "Deal 6 damage.",
            description_es: "Inflige 6 de daño.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::FlareSlashPlus),
        },
        CardId::FlareSlashPlus => CardData {
            id,
            slug: "flare_slash_plus",
            name_en: "Strike+",
            name_es: "Golpe+",
            description_en: "Deal 9 damage.",
            description_es: "Inflige 9 de daño.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::GuardStep => CardData {
            id,
            slug: "guard_step",
            name_en: "Defend",
            name_es: "Defensa",
            description_en: "Gain 5 Shield.",
            description_es: "Gana 5 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::GuardStepPlus),
        },
        CardId::GuardStepPlus => CardData {
            id,
            slug: "guard_step_plus",
            name_en: "Defend+",
            name_es: "Defensa+",
            description_en: "Gain 8 Shield.",
            description_es: "Gana 8 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Slipstream => CardData {
            id,
            slug: "slipstream",
            name_en: "Reposition",
            name_es: "Reposición",
            description_en: "Gain Rhythm +1. Draw 1. Gain 2 Shield.",
            description_es: "Gana Ritmo +1. Roba 1. Gana 2 de Escudo.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SlipstreamPlus),
        },
        CardId::SlipstreamPlus => CardData {
            id,
            slug: "slipstream_plus",
            name_en: "Reposition+",
            name_es: "Reposición+",
            description_en: "Gain Rhythm +1. Draw 1. Gain 4 Shield.",
            description_es: "Gana Ritmo +1. Roba 1. Gana 4 de Escudo.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::QuickStrike => CardData {
            id,
            slug: "quick_strike",
            name_en: "Quick Strike",
            name_es: "Golpe Veloz",
            description_en: "Deal 5 damage. Draw 1.",
            description_es: "Inflige 5 de daño. Roba 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::QuickStrikePlus),
        },
        CardId::QuickStrikePlus => CardData {
            id,
            slug: "quick_strike_plus",
            name_en: "Quick Strike+",
            name_es: "Golpe Veloz+",
            description_en: "Deal 7 damage. Draw 1.",
            description_es: "Inflige 7 de daño. Roba 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Reinforce => CardData {
            id,
            slug: "reinforce",
            name_en: "Reinforce",
            name_es: "Refuerzo",
            description_en: "Gain Rhythm +1. Gain 8 Shield.",
            description_es: "Gana Ritmo +1. Gana 8 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ReinforcePlus),
        },
        CardId::ReinforcePlus => CardData {
            id,
            slug: "reinforce_plus",
            name_en: "Reinforce+",
            name_es: "Refuerzo+",
            description_en: "Gain Rhythm +2. Gain 11 Shield.",
            description_es: "Gana Ritmo +2. Gana 11 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PressurePoint => CardData {
            id,
            slug: "pressure_point",
            name_en: "Pressure Point",
            name_es: "Punto de Presión",
            description_en: "Deal 4 damage. Apply Focus -1.",
            description_es: "Inflige 4 de daño. Aplica Enfoque -1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PressurePointPlus),
        },
        CardId::PressurePointPlus => CardData {
            id,
            slug: "pressure_point_plus",
            name_en: "Pressure Point+",
            name_es: "Punto de Presión+",
            description_en: "Deal 6 damage. Apply Focus -2.",
            description_es: "Inflige 6 de daño. Aplica Enfoque -2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::SunderingArc => CardData {
            id,
            slug: "sundering_arc",
            name_en: "Precise Strike",
            name_es: "Golpe Preciso",
            description_en: "Deal 12 damage. Apply Momentum -1.",
            description_es: "Inflige 12 de daño. Aplica Impulso -1.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SunderingArcPlus),
        },
        CardId::SunderingArcPlus => CardData {
            id,
            slug: "sundering_arc_plus",
            name_en: "Precise Strike+",
            name_es: "Golpe Preciso+",
            description_en: "Deal 16 damage. Apply Momentum -1.",
            description_es: "Inflige 16 de daño. Aplica Impulso -1.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::TwinStrike => CardData {
            id,
            slug: "twin_strike",
            name_en: "Twin Strike",
            name_es: "Golpe Doble",
            description_en: "Deal 4 damage twice.",
            description_es: "Inflige 4 de daño dos veces.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::TwinStrikePlus),
        },
        CardId::TwinStrikePlus => CardData {
            id,
            slug: "twin_strike_plus",
            name_en: "Twin Strike+",
            name_es: "Golpe Doble+",
            description_en: "Deal 5 damage twice.",
            description_es: "Inflige 5 de daño dos veces.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::BarrierField => CardData {
            id,
            slug: "barrier_field",
            name_en: "Barrier Field",
            name_es: "Campo de Barrera",
            description_en: "Gain 10 Shield. Apply Focus -1.",
            description_es: "Gana 10 de Escudo. Aplica Enfoque -1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::BarrierFieldPlus),
        },
        CardId::BarrierFieldPlus => CardData {
            id,
            slug: "barrier_field_plus",
            name_en: "Barrier Field+",
            name_es: "Campo de Barrera+",
            description_en: "Gain 13 Shield. Apply Focus -2.",
            description_es: "Gana 13 de Escudo. Aplica Enfoque -2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::TacticalBurst => CardData {
            id,
            slug: "tactical_burst",
            name_en: "Tactical Burst",
            name_es: "Impulso Táctico",
            description_en: "Draw 2. Gain Focus +1.",
            description_es: "Roba 2. Gana Enfoque +1.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::TacticalBurstPlus),
        },
        CardId::TacticalBurstPlus => CardData {
            id,
            slug: "tactical_burst_plus",
            name_en: "Tactical Burst+",
            name_es: "Impulso Táctico+",
            description_en: "Draw 2. Gain Focus +2.",
            description_es: "Roba 2. Gana Enfoque +2.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::RazorNet => CardData {
            id,
            slug: "razor_net",
            name_en: "Razor Net",
            name_es: "Red Cortante",
            description_en: "Deal 4 damage twice. Apply Bleed 2.",
            description_es: "Inflige 4 de daño dos veces. Aplica Sangrado 2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::RazorNetPlus),
        },
        CardId::RazorNetPlus => CardData {
            id,
            slug: "razor_net_plus",
            name_en: "Razor Net+",
            name_es: "Red Cortante+",
            description_en: "Deal 5 damage twice. Apply Bleed 2.",
            description_es: "Inflige 5 de daño dos veces. Aplica Sangrado 2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::BreachSignal => CardData {
            id,
            slug: "breach_signal",
            name_en: "Breach Signal",
            name_es: "Señal de Brecha",
            description_en: "Deal 7 damage. Draw 1. Apply Momentum -2.",
            description_es: "Inflige 7 de daño. Roba 1. Aplica Impulso -2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 2,
            traits: traits(false, false),
            upgrade: Some(CardId::BreachSignalPlus),
        },
        CardId::BreachSignalPlus => CardData {
            id,
            slug: "breach_signal_plus",
            name_en: "Breach Signal+",
            name_es: "Señal de Brecha+",
            description_en: "Deal 9 damage. Draw 1. Apply Momentum -2.",
            description_es: "Inflige 9 de daño. Roba 1. Aplica Impulso -2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 2,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::AnchorLoop => CardData {
            id,
            slug: "anchor_loop",
            name_en: "Anchor Loop",
            name_es: "Bucle de Anclaje",
            description_en: "Gain 14 Shield. Draw 2.",
            description_es: "Gana 14 de Escudo. Roba 2.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 3,
            traits: traits(false, false),
            upgrade: Some(CardId::AnchorLoopPlus),
        },
        CardId::AnchorLoopPlus => CardData {
            id,
            slug: "anchor_loop_plus",
            name_en: "Anchor Loop+",
            name_es: "Bucle de Anclaje+",
            description_en: "Gain 17 Shield. Draw 2.",
            description_es: "Gana 17 de Escudo. Roba 2.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 3,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ExecutionBeam => CardData {
            id,
            slug: "execution_beam",
            name_en: "Execution Beam",
            name_es: "Rayo de Ejecución",
            description_en: "Deal 20 damage.",
            description_es: "Inflige 20 de daño.",
            cost: 3,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ExecutionBeamPlus),
        },
        CardId::ExecutionBeamPlus => CardData {
            id,
            slug: "execution_beam_plus",
            name_en: "Execution Beam+",
            name_es: "Rayo de Ejecución+",
            description_en: "Deal 26 damage.",
            description_es: "Inflige 26 de daño.",
            cost: 3,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::FortressMatrix => CardData {
            id,
            slug: "fortress_matrix",
            name_en: "Fortress Matrix",
            name_es: "Matriz de Fortaleza",
            description_en: "Gain 16 Shield. Draw 1.",
            description_es: "Gana 16 de Escudo. Roba 1.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::FortressMatrixPlus),
        },
        CardId::FortressMatrixPlus => CardData {
            id,
            slug: "fortress_matrix_plus",
            name_en: "Fortress Matrix+",
            name_es: "Matriz de Fortaleza+",
            description_en: "Gain 20 Shield. Draw 1.",
            description_es: "Gana 20 de Escudo. Roba 1.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ZeroPoint => CardData {
            id,
            slug: "zero_point",
            name_en: "Zero Point",
            name_es: "Punto Cero",
            description_en: "Deal 10 damage. Draw 1. Apply Momentum -2.",
            description_es: "Inflige 10 de daño. Roba 1. Aplica Impulso -2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ZeroPointPlus),
        },
        CardId::ZeroPointPlus => CardData {
            id,
            slug: "zero_point_plus",
            name_en: "Zero Point+",
            name_es: "Punto Cero+",
            description_en: "Deal 14 damage. Draw 1. Apply Momentum -2.",
            description_es: "Inflige 14 de daño. Roba 1. Aplica Impulso -2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PinpointJab => CardData {
            id,
            slug: "pinpoint_jab",
            name_en: "Pinpoint Jab",
            name_es: "Golpe Certero",
            description_en: "Deal 5 damage. Apply Bleed 1.",
            description_es: "Inflige 5 de daño. Aplica Sangrado 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PinpointJabPlus),
        },
        CardId::PinpointJabPlus => CardData {
            id,
            slug: "pinpoint_jab_plus",
            name_en: "Pinpoint Jab+",
            name_es: "Golpe Certero+",
            description_en: "Deal 7 damage. Apply Bleed 1.",
            description_es: "Inflige 7 de daño. Aplica Sangrado 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::SignalTap => CardData {
            id,
            slug: "signal_tap",
            name_en: "Signal Tap",
            name_es: "Pulso de Señal",
            description_en: "Apply Momentum -1. Draw 1.",
            description_es: "Aplica Impulso -1. Roba 1.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SignalTapPlus),
        },
        CardId::SignalTapPlus => CardData {
            id,
            slug: "signal_tap_plus",
            name_en: "Signal Tap+",
            name_es: "Pulso de Señal+",
            description_en: "Apply Momentum -1. Draw 1. Gain 3 Shield.",
            description_es: "Aplica Impulso -1. Roba 1. Gana 3 de Escudo.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::BurstArray => CardData {
            id,
            slug: "burst_array",
            name_en: "Burst Array",
            name_es: "Ráfaga en Serie",
            description_en: "Deal 3 damage three times.",
            description_es: "Inflige 3 de daño tres veces.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::BurstArrayPlus),
        },
        CardId::BurstArrayPlus => CardData {
            id,
            slug: "burst_array_plus",
            name_en: "Burst Array+",
            name_es: "Ráfaga en Serie+",
            description_en: "Deal 4 damage three times.",
            description_es: "Inflige 4 de daño tres veces.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::CoverPulse => CardData {
            id,
            slug: "cover_pulse",
            name_en: "Cover Pulse",
            name_es: "Pulso de Cobertura",
            description_en: "Gain 6 Shield. Draw 1.",
            description_es: "Gana 6 de Escudo. Roba 1.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::CoverPulsePlus),
        },
        CardId::CoverPulsePlus => CardData {
            id,
            slug: "cover_pulse_plus",
            name_en: "Cover Pulse+",
            name_es: "Pulso de Cobertura+",
            description_en: "Gain 8 Shield. Draw 1.",
            description_es: "Gana 8 de Escudo. Roba 1.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::FracturePulse => CardData {
            id,
            slug: "fracture_pulse",
            name_en: "Fracture Pulse",
            name_es: "Pulso de Fractura",
            description_en: "Deal 9 damage. Apply Bleed 3.",
            description_es: "Inflige 9 de daño. Aplica Sangrado 3.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::FracturePulsePlus),
        },
        CardId::FracturePulsePlus => CardData {
            id,
            slug: "fracture_pulse_plus",
            name_en: "Fracture Pulse+",
            name_es: "Pulso de Fractura+",
            description_en: "Deal 12 damage. Apply Bleed 3.",
            description_es: "Inflige 12 de daño. Aplica Sangrado 3.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::VectorLock => CardData {
            id,
            slug: "vector_lock",
            name_en: "Vector Lock",
            name_es: "Bloqueo Vectorial",
            description_en: "Deal 6 damage. Apply Momentum -2. Gain 5 Shield.",
            description_es: "Inflige 6 de daño. Aplica Impulso -2. Gana 5 de Escudo.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::VectorLockPlus),
        },
        CardId::VectorLockPlus => CardData {
            id,
            slug: "vector_lock_plus",
            name_en: "Vector Lock+",
            name_es: "Bloqueo Vectorial+",
            description_en: "Deal 8 damage. Apply Momentum -2. Gain 6 Shield.",
            description_es: "Inflige 8 de daño. Aplica Impulso -2. Gana 6 de Escudo.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ChainBarrage => CardData {
            id,
            slug: "chain_barrage",
            name_en: "Chain Barrage",
            name_es: "Andanada en Cadena",
            description_en: "Deal 8 damage twice. Apply Bleed 2.",
            description_es: "Inflige 8 de daño dos veces. Aplica Sangrado 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ChainBarragePlus),
        },
        CardId::ChainBarragePlus => CardData {
            id,
            slug: "chain_barrage_plus",
            name_en: "Chain Barrage+",
            name_es: "Andanada en Cadena+",
            description_en: "Deal 10 damage twice. Apply Bleed 2.",
            description_es: "Inflige 10 de daño dos veces. Aplica Sangrado 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::OverwatchGrid => CardData {
            id,
            slug: "overwatch_grid",
            name_en: "Overwatch Grid",
            name_es: "Red de Vigilancia",
            description_en: "Gain 18 Shield. Draw 2.",
            description_es: "Gana 18 de Escudo. Roba 2.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::OverwatchGridPlus),
        },
        CardId::OverwatchGridPlus => CardData {
            id,
            slug: "overwatch_grid_plus",
            name_en: "Overwatch Grid+",
            name_es: "Red de Vigilancia+",
            description_en: "Gain 22 Shield. Draw 2.",
            description_es: "Gana 22 de Escudo. Roba 2.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::RiftDart => CardData {
            id,
            slug: "rift_dart",
            name_en: "Rift Dart",
            name_es: "Dardo de Brecha",
            description_en: "Deal 4 damage. Apply Bleed 1. If target Momentum < 0, draw 1.",
            description_es: "Inflige 4 de daño. Aplica Sangrado 1. Si el objetivo tiene Impulso < 0, roba 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::RiftDartPlus),
        },
        CardId::RiftDartPlus => CardData {
            id,
            slug: "rift_dart_plus",
            name_en: "Rift Dart+",
            name_es: "Dardo de Brecha+",
            description_en: "Deal 6 damage. Apply Bleed 1. If target Momentum < 0, draw 1.",
            description_es: "Inflige 6 de daño. Aplica Sangrado 1. Si el objetivo tiene Impulso < 0, roba 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::MarkPulse => CardData {
            id,
            slug: "mark_pulse",
            name_en: "Mark Pulse",
            name_es: "Pulso de Marca",
            description_en: "Apply Momentum -1. If target has Bleed, gain 4 Shield.",
            description_es: "Aplica Impulso -1. Si el objetivo tiene Sangrado, gana 4 de Escudo.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::MarkPulsePlus),
        },
        CardId::MarkPulsePlus => CardData {
            id,
            slug: "mark_pulse_plus",
            name_en: "Mark Pulse+",
            name_es: "Pulso de Marca+",
            description_en: "Apply Momentum -1. If target has Bleed, gain 6 Shield.",
            description_es: "Aplica Impulso -1. Si el objetivo tiene Sangrado, gana 6 de Escudo.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::BraceCircuit => CardData {
            id,
            slug: "brace_circuit",
            name_en: "Brace Circuit",
            name_es: "Circuito de Refuerzo",
            description_en: "Gain 6 Shield. If you already have Shield, draw 1.",
            description_es: "Gana 6 de Escudo. Si ya tienes Escudo, roba 1.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::BraceCircuitPlus),
        },
        CardId::BraceCircuitPlus => CardData {
            id,
            slug: "brace_circuit_plus",
            name_en: "Brace Circuit+",
            name_es: "Circuito de Refuerzo+",
            description_en: "Gain 8 Shield. If you already have Shield, draw 1.",
            description_es: "Gana 8 de Escudo. Si ya tienes Escudo, roba 1.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::FaultShot => CardData {
            id,
            slug: "fault_shot",
            name_en: "Fault Shot",
            name_es: "Disparo de Falla",
            description_en: "Deal 5 damage. If target Focus < 0, gain Focus +1.",
            description_es: "Inflige 5 de daño. Si el objetivo tiene Enfoque < 0, gana Enfoque +1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::FaultShotPlus),
        },
        CardId::FaultShotPlus => CardData {
            id,
            slug: "fault_shot_plus",
            name_en: "Fault Shot+",
            name_es: "Disparo de Falla+",
            description_en: "Deal 7 damage. If target Focus < 0, gain Focus +1.",
            description_es: "Inflige 7 de daño. Si el objetivo tiene Enfoque < 0, gana Enfoque +1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::SeverArc => CardData {
            id,
            slug: "sever_arc",
            name_en: "Sever Arc",
            name_es: "Arco de Corte",
            description_en: "Deal 8 damage. If target has Bleed, deal 8 damage again.",
            description_es: "Inflige 8 de daño. Si el objetivo tiene Sangrado, inflige 8 de daño otra vez.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SeverArcPlus),
        },
        CardId::SeverArcPlus => CardData {
            id,
            slug: "sever_arc_plus",
            name_en: "Sever Arc+",
            name_es: "Arco de Corte+",
            description_en: "Deal 10 damage. If target has Bleed, deal 10 damage again.",
            description_es: "Inflige 10 de daño. Si el objetivo tiene Sangrado, inflige 10 de daño otra vez.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Lockbreaker => CardData {
            id,
            slug: "lockbreaker",
            name_en: "Lockbreaker",
            name_es: "Rompebloqueo",
            description_en: "Deal 6 damage. If target Focus < 0, apply Focus -1 and gain 6 Shield.",
            description_es: "Inflige 6 de daño. Si el objetivo tiene Enfoque < 0, aplica Enfoque -1 y gana 6 de Escudo.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::LockbreakerPlus),
        },
        CardId::LockbreakerPlus => CardData {
            id,
            slug: "lockbreaker_plus",
            name_en: "Lockbreaker+",
            name_es: "Rompebloqueo+",
            description_en: "Deal 8 damage. If target Focus < 0, apply Focus -1 and gain 8 Shield.",
            description_es: "Inflige 8 de daño. Si el objetivo tiene Enfoque < 0, aplica Enfoque -1 y gana 8 de Escudo.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::CounterLattice => CardData {
            id,
            slug: "counter_lattice",
            name_en: "Counter Lattice",
            name_es: "Trama de Respuesta",
            description_en: "Deal 6 damage. If target Focus < 0, gain 1 Energy.",
            description_es: "Inflige 6 de daño. Si el objetivo tiene Enfoque < 0, gana 1 de Energía.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::CounterLatticePlus),
        },
        CardId::CounterLatticePlus => CardData {
            id,
            slug: "counter_lattice_plus",
            name_en: "Counter Lattice+",
            name_es: "Trama de Respuesta+",
            description_en: "Deal 8 damage. If target Focus < 0, gain 1 Energy.",
            description_es: "Inflige 8 de daño. Si el objetivo tiene Enfoque < 0, gana 1 de Energía.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::TerminalLoop => CardData {
            id,
            slug: "terminal_loop",
            name_en: "Terminal Loop",
            name_es: "Bucle Terminal",
            description_en: "Deal 12 damage. If target has Bleed, draw 1. If target Momentum < 0, gain Focus +1.",
            description_es: "Inflige 12 de daño. Si el objetivo tiene Sangrado, roba 1. Si el objetivo tiene Impulso < 0, gana Enfoque +1.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::TerminalLoopPlus),
        },
        CardId::TerminalLoopPlus => CardData {
            id,
            slug: "terminal_loop_plus",
            name_en: "Terminal Loop+",
            name_es: "Bucle Terminal+",
            description_en: "Deal 15 damage. If target has Bleed, draw 1. If target Momentum < 0, gain Focus +2.",
            description_es: "Inflige 15 de daño. Si el objetivo tiene Sangrado, roba 1. Si el objetivo tiene Impulso < 0, gana Enfoque +2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ArcSpark => CardData {
            id,
            slug: "arc_spark",
            name_en: "Arc Spark",
            name_es: "Chispa de Arco",
            description_en: "Deal 4 damage. Gain Momentum +2.",
            description_es: "Inflige 4 de daño. Gana Impulso +2.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ArcSparkPlus),
        },
        CardId::ArcSparkPlus => CardData {
            id,
            slug: "arc_spark_plus",
            name_en: "Arc Spark+",
            name_es: "Chispa de Arco+",
            description_en: "Deal 6 damage. Gain Momentum +3.",
            description_es: "Inflige 6 de daño. Gana Impulso +3.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::CapacitiveShell => CardData {
            id,
            slug: "capacitive_shell",
            name_en: "Capacitive Shell",
            name_es: "Cascarón Capacitivo",
            description_en: "Gain 5 Shield. Gain Momentum +2.",
            description_es: "Gana 5 de Escudo. Gana Impulso +2.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::CapacitiveShellPlus),
        },
        CardId::CapacitiveShellPlus => CardData {
            id,
            slug: "capacitive_shell_plus",
            name_en: "Capacitive Shell+",
            name_es: "Cascarón Capacitivo+",
            description_en: "Gain 8 Shield. Gain Momentum +3.",
            description_es: "Gana 8 de Escudo. Gana Impulso +3.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PrimeRoutine => CardData {
            id,
            slug: "prime_routine",
            name_en: "Prime Routine",
            name_es: "Rutina Inicial",
            description_en: "Draw 2. Gain Momentum +2.",
            description_es: "Roba 2. Gana Impulso +2.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PrimeRoutinePlus),
        },
        CardId::PrimeRoutinePlus => CardData {
            id,
            slug: "prime_routine_plus",
            name_en: "Prime Routine+",
            name_es: "Rutina Inicial+",
            description_en: "Draw 3. Gain Momentum +3.",
            description_es: "Roba 3. Gana Impulso +3.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Stockpile => CardData {
            id,
            slug: "stockpile",
            name_en: "Stockpile",
            name_es: "Acopio",
            description_en: "Gain Momentum +3.",
            description_es: "Gana Impulso +3.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::StockpilePlus),
        },
        CardId::StockpilePlus => CardData {
            id,
            slug: "stockpile_plus",
            name_en: "Stockpile+",
            name_es: "Acopio+",
            description_en: "Gain Momentum +4.",
            description_es: "Gana Impulso +4.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PulseConverter => CardData {
            id,
            slug: "pulse_converter",
            name_en: "Distraction",
            name_es: "Distracción",
            description_en: "Requires Rhythm > 1. Set target Focus to 0.",
            description_es: "Requiere Ritmo > 1. Fija el Enfoque del objetivo en 0.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PulseConverterPlus),
        },
        CardId::PulseConverterPlus => CardData {
            id,
            slug: "pulse_converter_plus",
            name_en: "Distraction+",
            name_es: "Distracción+",
            description_en: "Requires Rhythm > 1. Set target Focus to 0. Draw 1.",
            description_es: "Requiere Ritmo > 1. Fija el Enfoque del objetivo en 0. Roba 1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Bulwark,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ReservoirGuard => CardData {
            id,
            slug: "reservoir_guard",
            name_en: "Reservoir Guard",
            name_es: "Guardia de Reserva",
            description_en: "Gain 10 Shield. If Momentum > 1, gain 1 Energy.",
            description_es: "Gana 10 de Escudo. Si Impulso > 1, gana 1 de Energía.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ReservoirGuardPlus),
        },
        CardId::ReservoirGuardPlus => CardData {
            id,
            slug: "reservoir_guard_plus",
            name_en: "Reservoir Guard+",
            name_es: "Guardia de Reserva+",
            description_en: "Gain 13 Shield. If Momentum > 1, gain 1 Energy.",
            description_es: "Gana 13 de Escudo. Si Impulso > 1, gana 1 de Energía.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::VoltaicDrive => CardData {
            id,
            slug: "voltaic_drive",
            name_en: "Voltaic Drive",
            name_es: "Impulso Voltaico",
            description_en: "Deal 11 damage. If Momentum > 1, draw 2.",
            description_es: "Inflige 11 de daño. Si Impulso > 1, roba 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 2,
            traits: traits(false, false),
            upgrade: Some(CardId::VoltaicDrivePlus),
        },
        CardId::VoltaicDrivePlus => CardData {
            id,
            slug: "voltaic_drive_plus",
            name_en: "Voltaic Drive+",
            name_es: "Impulso Voltaico+",
            description_en: "Deal 14 damage. If Momentum > 1, draw 2.",
            description_es: "Inflige 14 de daño. Si Impulso > 1, roba 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Momentum,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 2,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::StormVault => CardData {
            id,
            slug: "storm_vault",
            name_en: "Freeze",
            name_es: "Congelar",
            description_en: "Set Momentum to 0 for all fighters.",
            description_es: "Fija el Impulso de todos los combatientes en 0.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::StormVaultPlus),
        },
        CardId::StormVaultPlus => CardData {
            id,
            slug: "storm_vault_plus",
            name_en: "Freeze+",
            name_es: "Congelar+",
            description_en: "Set Momentum to 0 for all fighters. Draw 1.",
            description_es: "Fija el Impulso de todos los combatientes en 0. Roba 1.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Pressure,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::SparkSmith => CardData {
            id,
            slug: "spark_smith",
            name_en: "Spark Smith",
            name_es: "Forja de Chispas",
            description_en: "Draw 1. Add Spark to your hand.",
            description_es: "Roba 1. Añade Chispa a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SparkSmithPlus),
        },
        CardId::SparkSmithPlus => CardData {
            id,
            slug: "spark_smith_plus",
            name_en: "Spark Smith+",
            name_es: "Forja de Chispas+",
            description_en: "Draw 2. Add Spark to your hand.",
            description_es: "Roba 2. Añade Chispa a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PatchBay => CardData {
            id,
            slug: "patch_bay",
            name_en: "Patch Bay",
            name_es: "Bahía de Parches",
            description_en: "Gain 6 Shield. Add Patch to your hand.",
            description_es: "Gana 6 de Escudo. Añade Parche a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PatchBayPlus),
        },
        CardId::PatchBayPlus => CardData {
            id,
            slug: "patch_bay_plus",
            name_en: "Patch Bay+",
            name_es: "Bahía de Parches+",
            description_en: "Gain 8 Shield. Add Patch to your hand.",
            description_es: "Gana 8 de Escudo. Añade Parche a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::TracerWeave => CardData {
            id,
            slug: "tracer_weave",
            name_en: "Tracer Weave",
            name_es: "Trama de Rastreo",
            description_en: "Deal 4 damage. Add Tracer to your hand.",
            description_es: "Inflige 4 de daño. Añade Rastreador a tu mano.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::TracerWeavePlus),
        },
        CardId::TracerWeavePlus => CardData {
            id,
            slug: "tracer_weave_plus",
            name_en: "Tracer Weave+",
            name_es: "Trama de Rastreo+",
            description_en: "Deal 6 damage. Add Tracer to your hand.",
            description_es: "Inflige 6 de daño. Añade Rastreador a tu mano.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::NeedleNest => CardData {
            id,
            slug: "needle_nest",
            name_en: "Needle Nest",
            name_es: "Nido de Agujas",
            description_en: "Deal 3 damage. Add Needler to your hand.",
            description_es: "Inflige 3 de daño. Añade Aguja a tu mano.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::NeedleNestPlus),
        },
        CardId::NeedleNestPlus => CardData {
            id,
            slug: "needle_nest_plus",
            name_en: "Needle Nest+",
            name_es: "Nido de Agujas+",
            description_en: "Deal 5 damage. Add Needler to your hand.",
            description_es: "Inflige 5 de daño. Añade Aguja a tu mano.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::AssemblyLine => CardData {
            id,
            slug: "assembly_line",
            name_en: "Assembly Line",
            name_es: "Línea de Montaje",
            description_en: "Draw 1. Add Spark and Patch to your hand.",
            description_es: "Roba 1. Añade Chispa y Parche a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::AssemblyLinePlus),
        },
        CardId::AssemblyLinePlus => CardData {
            id,
            slug: "assembly_line_plus",
            name_en: "Assembly Line+",
            name_es: "Línea de Montaje+",
            description_en: "Draw 2. Add Spark and Patch to your hand.",
            description_es: "Roba 2. Añade Chispa y Parche a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ToolCache => CardData {
            id,
            slug: "tool_cache",
            name_en: "Tool Cache",
            name_es: "Alijo de Herramientas",
            description_en: "Draw 1. Add Tracer and Needler to your hand.",
            description_es: "Roba 1. Añade Rastreador y Aguja a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ToolCachePlus),
        },
        CardId::ToolCachePlus => CardData {
            id,
            slug: "tool_cache_plus",
            name_en: "Tool Cache+",
            name_es: "Alijo de Herramientas+",
            description_en: "Draw 2. Add Tracer and Needler to your hand.",
            description_es: "Roba 2. Añade Rastreador y Aguja a tu mano.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ImprovisedArsenal => CardData {
            id,
            slug: "improvised_arsenal",
            name_en: "Improvised Arsenal",
            name_es: "Arsenal Improvisado",
            description_en: "Draw 1. Add Spark, Patch, Tracer, and Needler to your discard pile.",
            description_es: "Roba 1. Añade Chispa, Parche, Rastreador y Aguja a tu pila de descarte.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 3,
            traits: traits(false, false),
            upgrade: Some(CardId::ImprovisedArsenalPlus),
        },
        CardId::ImprovisedArsenalPlus => CardData {
            id,
            slug: "improvised_arsenal_plus",
            name_en: "Improvised Arsenal+",
            name_es: "Arsenal Improvisado+",
            description_en: "Draw 2. Add Spark, Patch, Tracer, and Needler to your discard pile.",
            description_es: "Roba 2. Añade Chispa, Parche, Rastreador y Aguja a tu pila de descarte.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 3,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ForgeStorm => CardData {
            id,
            slug: "forge_storm",
            name_en: "Forge Storm",
            name_es: "Tormenta de Forja",
            description_en: "Draw 1. Add Spark, Patch, Tracer, and Needler to your hand.",
            description_es: "Roba 1. Añade Chispa, Parche, Rastreador y Aguja a tu mano.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ForgeStormPlus),
        },
        CardId::ForgeStormPlus => CardData {
            id,
            slug: "forge_storm_plus",
            name_en: "Forge Storm+",
            name_es: "Tormenta de Forja+",
            description_en: "Draw 2. Add Spark, Patch, Tracer, and Needler to your hand.",
            description_es: "Roba 2. Añade Chispa, Parche, Rastreador y Aguja a tu mano.",
            cost: 2,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::SweepPulse => CardData {
            id,
            slug: "sweep_pulse",
            name_en: "Sweep Pulse",
            name_es: "Pulso de Barrido",
            description_en: "Deal 4 damage to all enemies.",
            description_es: "Inflige 4 de daño a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SweepPulsePlus),
        },
        CardId::SweepPulsePlus => CardData {
            id,
            slug: "sweep_pulse_plus",
            name_en: "Sweep Pulse+",
            name_es: "Pulso de Barrido+",
            description_en: "Deal 6 damage to all enemies.",
            description_es: "Inflige 6 de daño a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::DimmingWave => CardData {
            id,
            slug: "dimming_wave",
            name_en: "Dimming Wave",
            name_es: "Onda Atenuante",
            description_en: "Apply Focus -1 to all enemies.",
            description_es: "Aplica Enfoque -1 a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::DimmingWavePlus),
        },
        CardId::DimmingWavePlus => CardData {
            id,
            slug: "dimming_wave_plus",
            name_en: "Dimming Wave+",
            name_es: "Onda Atenuante+",
            description_en: "Apply Focus -2 to all enemies.",
            description_es: "Aplica Enfoque -2 a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ShrapnelVeil => CardData {
            id,
            slug: "shrapnel_veil",
            name_en: "Shrapnel Veil",
            name_es: "Velo de Esquirlas",
            description_en: "Deal 2 damage to all enemies. Gain 4 Shield.",
            description_es: "Inflige 2 de daño a todos los enemigos. Gana 4 de Escudo.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ShrapnelVeilPlus),
        },
        CardId::ShrapnelVeilPlus => CardData {
            id,
            slug: "shrapnel_veil_plus",
            name_en: "Shrapnel Veil+",
            name_es: "Velo de Esquirlas+",
            description_en: "Deal 3 damage to all enemies. Gain 6 Shield.",
            description_es: "Inflige 3 de daño a todos los enemigos. Gana 6 de Escudo.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::ScouringWind => CardData {
            id,
            slug: "scouring_wind",
            name_en: "Scouring Wind",
            name_es: "Viento de Barrido",
            description_en: "Deal 6 damage to all enemies. Apply Bleed 1.",
            description_es: "Inflige 6 de daño a todos los enemigos. Aplica Sangrado 1.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::ScouringWindPlus),
        },
        CardId::ScouringWindPlus => CardData {
            id,
            slug: "scouring_wind_plus",
            name_en: "Scouring Wind+",
            name_es: "Viento de Barrido+",
            description_en: "Deal 8 damage to all enemies. Apply Bleed 2.",
            description_es: "Inflige 8 de daño a todos los enemigos. Aplica Sangrado 2.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::CollapsePattern => CardData {
            id,
            slug: "collapse_pattern",
            name_en: "Collapse Pattern",
            name_es: "Patrón de Colapso",
            description_en: "Apply Momentum -1 to all enemies. Draw 1.",
            description_es: "Aplica Impulso -1 a todos los enemigos. Roba 1.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::CollapsePatternPlus),
        },
        CardId::CollapsePatternPlus => CardData {
            id,
            slug: "collapse_pattern_plus",
            name_en: "Collapse Pattern+",
            name_es: "Patrón de Colapso+",
            description_en: "Apply Momentum -2 to all enemies. Draw 1.",
            description_es: "Aplica Impulso -2 a todos los enemigos. Roba 1.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Linebreaker => CardData {
            id,
            slug: "linebreaker",
            name_en: "Linebreaker",
            name_es: "Rompelíneas",
            description_en: "Piercing. Deal 5 damage to all enemies.",
            description_es: "Perforante. Inflige 5 de daño a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, true),
            upgrade: Some(CardId::LinebreakerPlus),
        },
        CardId::LinebreakerPlus => CardData {
            id,
            slug: "linebreaker_plus",
            name_en: "Linebreaker+",
            name_es: "Rompelíneas+",
            description_en: "Piercing. Deal 7 damage to all enemies.",
            description_es: "Perforante. Inflige 7 de daño a todos los enemigos.",
            cost: 1,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, true),
            upgrade: None,
        },
        CardId::NovaCollapse => CardData {
            id,
            slug: "nova_collapse",
            name_en: "Nova Collapse",
            name_es: "Colapso Nova",
            description_en: "Piercing. Deal 9 damage to all enemies.",
            description_es: "Perforante. Inflige 9 de daño a todos los enemigos.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, true),
            upgrade: Some(CardId::NovaCollapsePlus),
        },
        CardId::NovaCollapsePlus => CardData {
            id,
            slug: "nova_collapse_plus",
            name_en: "Nova Collapse+",
            name_es: "Colapso Nova+",
            description_en: "Piercing. Deal 12 damage to all enemies.",
            description_es: "Perforante. Inflige 12 de daño a todos los enemigos.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, true),
            upgrade: None,
        },
        CardId::SuppressionNet => CardData {
            id,
            slug: "suppression_net",
            name_en: "Suppression Net",
            name_es: "Red de Supresión",
            description_en: "Gain 8 Shield. Apply Focus -1 and Momentum -1 to all enemies.",
            description_es: "Gana 8 de Escudo. Aplica Enfoque -1 e Impulso -1 a todos los enemigos.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::SuppressionNetPlus),
        },
        CardId::SuppressionNetPlus => CardData {
            id,
            slug: "suppression_net_plus",
            name_en: "Suppression Net+",
            name_es: "Red de Supresión+",
            description_en: "Gain 11 Shield. Apply Focus -2 and Momentum -1 to all enemies.",
            description_es: "Gana 11 de Escudo. Aplica Enfoque -2 e Impulso -1 a todos los enemigos.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Sweep,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::RazorRush => CardData {
            id,
            slug: "razor_rush",
            name_en: "Razor Rush",
            name_es: "Carga Cortante",
            description_en: "Deal 7 damage.",
            description_es: "Inflige 7 de daño.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::RazorRushPlus),
        },
        CardId::RazorRushPlus => CardData {
            id,
            slug: "razor_rush_plus",
            name_en: "Razor Rush+",
            name_es: "Carga Cortante+",
            description_en: "Deal 10 damage.",
            description_es: "Inflige 10 de daño.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::HardReset => CardData {
            id,
            slug: "hard_reset",
            name_en: "Hard Reset",
            name_es: "Reinicio Brusco",
            description_en: "Draw 2.",
            description_es: "Roba 2.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::HardResetPlus),
        },
        CardId::HardResetPlus => CardData {
            id,
            slug: "hard_reset_plus",
            name_en: "Hard Reset+",
            name_es: "Reinicio Brusco+",
            description_en: "Draw 3.",
            description_es: "Roba 3.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::EmergencyPlating => CardData {
            id,
            slug: "emergency_plating",
            name_en: "Emergency Plating",
            name_es: "Blindaje de Emergencia",
            description_en: "Gain 12 Shield.",
            description_es: "Gana 12 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::EmergencyPlatingPlus),
        },
        CardId::EmergencyPlatingPlus => CardData {
            id,
            slug: "emergency_plating_plus",
            name_en: "Emergency Plating+",
            name_es: "Blindaje de Emergencia+",
            description_en: "Gain 16 Shield.",
            description_es: "Gana 16 de Escudo.",
            cost: 1,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Combat),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Cauterize => CardData {
            id,
            slug: "cauterize",
            name_en: "Cauterize",
            name_es: "Cauteriza",
            description_en: "Deal 5 damage. Apply Focus -1 and Rhythm -1.",
            description_es: "Inflige 5 de daño. Aplica Enfoque -1 y Ritmo -1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::CauterizePlus),
        },
        CardId::CauterizePlus => CardData {
            id,
            slug: "cauterize_plus",
            name_en: "Cauterize+",
            name_es: "Cauteriza+",
            description_en: "Deal 7 damage. Apply Focus -2 and Rhythm -1.",
            description_es: "Inflige 7 de daño. Aplica Enfoque -2 y Ritmo -1.",
            cost: 1,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::EmberBurst => CardData {
            id,
            slug: "ember_burst",
            name_en: "Ember Burst",
            name_es: "Estallido de Ascua",
            description_en: "Gain 1 Energy. Draw 1.",
            description_es: "Gana 1 de Energía. Roba 1.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::EmberBurstPlus),
        },
        CardId::EmberBurstPlus => CardData {
            id,
            slug: "ember_burst_plus",
            name_en: "Ember Burst+",
            name_es: "Estallido de Ascua+",
            description_en: "Gain 1 Energy. Draw 2.",
            description_es: "Gana 1 de Energía. Roba 2.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::AshenVector => CardData {
            id,
            slug: "ashen_vector",
            name_en: "Ashen Vector",
            name_es: "Vector de Ceniza",
            description_en: "Deal 12 damage. Draw 1.",
            description_es: "Inflige 12 de daño. Roba 1.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::AshenVectorPlus),
        },
        CardId::AshenVectorPlus => CardData {
            id,
            slug: "ashen_vector_plus",
            name_en: "Ashen Vector+",
            name_es: "Vector de Ceniza+",
            description_en: "Deal 15 damage. Draw 2.",
            description_es: "Inflige 15 de daño. Roba 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Elite),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::PurgeArray => CardData {
            id,
            slug: "purge_array",
            name_en: "Purge Array",
            name_es: "Matriz de Purga",
            description_en: "Deal 7 damage to all enemies twice.",
            description_es: "Inflige 7 de daño a todos los enemigos dos veces.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::PurgeArrayPlus),
        },
        CardId::PurgeArrayPlus => CardData {
            id,
            slug: "purge_array_plus",
            name_en: "Purge Array+",
            name_es: "Matriz de Purga+",
            description_en: "Deal 9 damage to all enemies twice.",
            description_es: "Inflige 9 de daño a todos los enemigos dos veces.",
            cost: 2,
            target: CardTarget::AllEnemies,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::LastProtocol => CardData {
            id,
            slug: "last_protocol",
            name_en: "Last Protocol",
            name_es: "Último Protocolo",
            description_en: "Deal 18 damage. Gain 1 Energy. Draw 1.",
            description_es: "Inflige 18 de daño. Gana 1 de Energía. Roba 1.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: Some(CardId::LastProtocolPlus),
        },
        CardId::LastProtocolPlus => CardData {
            id,
            slug: "last_protocol_plus",
            name_en: "Last Protocol+",
            name_es: "Último Protocolo+",
            description_en: "Deal 22 damage. Gain 1 Energy. Draw 2.",
            description_es: "Inflige 22 de daño. Gana 1 de Energía. Roba 2.",
            cost: 2,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Burst,
            reward_tier: Some(RewardTier::Boss),
            elite_unlock_level: 1,
            traits: traits(false, false),
            upgrade: None,
        },
        CardId::Spark => CardData {
            id,
            slug: "spark",
            name_en: "Spark",
            name_es: "Chispa",
            description_en: "Temporary. Deal 4 damage.",
            description_es: "Temporal. Inflige 4 de daño.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: None,
            elite_unlock_level: 1,
            traits: traits(true, false),
            upgrade: None,
        },
        CardId::Patch => CardData {
            id,
            slug: "patch",
            name_en: "Patch",
            name_es: "Parche",
            description_en: "Temporary. Gain 5 Shield.",
            description_es: "Temporal. Gana 5 de Escudo.",
            cost: 0,
            target: CardTarget::SelfOnly,
            archetype: CardArchetype::Fabricate,
            reward_tier: None,
            elite_unlock_level: 1,
            traits: traits(true, false),
            upgrade: None,
        },
        CardId::Tracer => CardData {
            id,
            slug: "tracer",
            name_en: "Tracer",
            name_es: "Rastreador",
            description_en: "Temporary. Apply Rhythm -1.",
            description_es: "Temporal. Aplica Ritmo -1.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: None,
            elite_unlock_level: 1,
            traits: traits(true, false),
            upgrade: None,
        },
        CardId::Needler => CardData {
            id,
            slug: "needler",
            name_en: "Needler",
            name_es: "Aguja",
            description_en: "Temporary. Deal 2 damage. Apply Bleed 1.",
            description_es: "Temporal. Inflige 2 de daño. Aplica Sangrado 1.",
            cost: 0,
            target: CardTarget::Enemy,
            archetype: CardArchetype::Fabricate,
            reward_tier: None,
            elite_unlock_level: 1,
            traits: traits(true, false),
            upgrade: None,
        },
    }
}
