#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 SVG_ICON ANDROID_RES_DIR" >&2
  exit 1
fi

SVG_ICON="$1"
ANDROID_RES_DIR="$2"
DRAWABLE_DIR="${ANDROID_RES_DIR}/drawable"
MIPMAP_DIR="${ANDROID_RES_DIR}/mipmap-anydpi-v26"
FOREGROUND_ICON="${DRAWABLE_DIR}/ic_launcher_foreground.xml"
LAUNCHER_ICON="${MIPMAP_DIR}/ic_launcher.xml"
ROUND_LAUNCHER_ICON="${MIPMAP_DIR}/ic_launcher_round.xml"

if [[ ! -f "$SVG_ICON" ]]; then
  echo "Missing launcher icon source: $SVG_ICON" >&2
  exit 1
fi

mkdir -p "$DRAWABLE_DIR" "$MIPMAP_DIR"

perl - "$SVG_ICON" >"$FOREGROUND_ICON" <<'PERL'
use strict;
use warnings;

my ($svg_path) = @ARGV;
open my $fh, '<', $svg_path or die "Could not read $svg_path: $!\n";
local $/;
my $svg = <$fh>;

sub attr {
  my ($attrs, $name) = @_;
  return $1 if $attrs =~ /\b\Q$name\E="([^"]+)"/;
  return $1 if $attrs =~ /\b\Q$name\E='([^']+)'/;
  die "Missing SVG attribute `$name` in launcher icon source.\n";
}

sub color {
  my ($raw) = @_;
  my $value = lc($raw);
  return "#$1$1$2$2$3$3" if $value =~ /^#([0-9a-f])([0-9a-f])([0-9a-f])$/;
  return $value if $value =~ /^#[0-9a-f]{6}$/;
  die "Unsupported SVG color `$raw` in launcher icon source.\n";
}

sub fmt {
  my ($value) = @_;
  my $text = sprintf('%.4f', $value + 0);
  $text =~ s/\.?0+$//;
  return $text eq '-0' ? '0' : $text;
}

sub circle_path {
  my ($cx, $cy, $r) = @_;
  my $k = $r * 0.5522847498307936;
  my $left = $cx - $r;
  my $right = $cx + $r;
  my $top = $cy - $r;
  my $bottom = $cy + $r;
  return join(' ',
    'M' . fmt($cx) . ',' . fmt($top),
    'C' . fmt($cx + $k) . ',' . fmt($top) . ' ' . fmt($right) . ',' . fmt($cy - $k) . ' ' . fmt($right) . ',' . fmt($cy),
    'C' . fmt($right) . ',' . fmt($cy + $k) . ' ' . fmt($cx + $k) . ',' . fmt($bottom) . ' ' . fmt($cx) . ',' . fmt($bottom),
    'C' . fmt($cx - $k) . ',' . fmt($bottom) . ' ' . fmt($left) . ',' . fmt($cy + $k) . ' ' . fmt($left) . ',' . fmt($cy),
    'C' . fmt($left) . ',' . fmt($cy - $k) . ' ' . fmt($cx - $k) . ',' . fmt($top) . ' ' . fmt($cx) . ',' . fmt($top),
    'Z',
  );
}

my ($view_x, $view_y, $view_w, $view_h) =
  $svg =~ /<svg\b[^>]*\bviewBox="([-+0-9.]+)\s+([-+0-9.]+)\s+([-+0-9.]+)\s+([-+0-9.]+)"/;
die "Launcher icon source needs a numeric SVG viewBox.\n" unless defined $view_h;
die "Launcher icon source viewBox must be positive.\n" unless $view_w > 0 && $view_h > 0;

my ($group_attrs) = $svg =~ /<g\b([^>]*)>/;
die "Launcher icon source needs a filled group for logo circles.\n" unless defined $group_attrs;
my $fill = color(attr($group_attrs, 'fill'));

my @circles;
while ($svg =~ /<circle\b([^>]*)\/?>/g) {
  my $attrs = $1;
  push @circles, [
    attr($attrs, 'cx') + 0,
    attr($attrs, 'cy') + 0,
    attr($attrs, 'r') + 0,
  ];
}
die "Launcher icon source needs at least one circle.\n" unless @circles;

my ($path_attrs) = $svg =~ /<path\b([^>]*)\/?>/;
die "Launcher icon source needs a stroked path for logo links.\n" unless defined $path_attrs;
my $stroke = color(attr($path_attrs, 'stroke'));
my $stroke_width = attr($path_attrs, 'stroke-width') + 0;
my $path_d = attr($path_attrs, 'd');
my @path_numbers = $path_d =~ /[-+]?(?:\d*\.)?\d+/g;
my @path_commands = $path_d =~ /[A-Za-z]/g;
die "Unsupported launcher icon path data `$path_d`.\n"
  unless @path_commands == 2 && $path_commands[0] eq 'M' && $path_commands[1] eq 'm' && @path_numbers == 8;

my ($start_x, $start_y, $line_x, $line_y, $move_dx, $move_dy, $line_dx, $line_dy) =
  map { $_ + 0 } @path_numbers;
my $second_start_x = $line_x + $move_dx;
my $second_start_y = $line_y + $move_dy;
my $second_end_x = $second_start_x + $line_dx;
my $second_end_y = $second_start_y + $line_dy;
my $line_path = join(' ',
  'M' . fmt($start_x) . ',' . fmt($start_y),
  'L' . fmt($line_x) . ',' . fmt($line_y),
  'M' . fmt($second_start_x) . ',' . fmt($second_start_y),
  'L' . fmt($second_end_x) . ',' . fmt($second_end_y),
);

my $canvas_size = 108;
my $logo_size = 48;
my $scale = $logo_size / ($view_w > $view_h ? $view_w : $view_h);
my $translate_x = ($canvas_size - ($view_w * $scale)) * 0.5 - ($view_x * $scale);
my $translate_y = ($canvas_size - ($view_h * $scale)) * 0.5 - ($view_y * $scale);

print <<"XML";
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/render-android-icons.sh from web/mazocarta.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:scaleX="@{[fmt($scale)]}"
        android:scaleY="@{[fmt($scale)]}"
        android:translateX="@{[fmt($translate_x)]}"
        android:translateY="@{[fmt($translate_y)]}">
        <path
            android:fillColor="\@android:color/transparent"
            android:pathData="$line_path"
            android:strokeColor="$stroke"
            android:strokeLineCap="butt"
            android:strokeWidth="@{[fmt($stroke_width)]}" />
XML

for my $circle (@circles) {
  my ($cx, $cy, $r) = @{$circle};
  my $path = circle_path($cx, $cy, $r);
  print <<"XML";
        <path
            android:fillColor="$fill"
            android:pathData="$path" />
XML
}

print <<"XML";
    </group>
</vector>
XML
PERL

cat >"$LAUNCHER_ICON" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/render-android-icons.sh from web/mazocarta.svg. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/mazocarta_black" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
XML

cat >"$ROUND_LAUNCHER_ICON" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/render-android-icons.sh from web/mazocarta.svg. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/mazocarta_black" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
XML
