#!/usr/bin/env node
import { build } from "esbuild";
import {
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const CHECK_MODE = process.argv.includes("--check");
const ROOT = resolve(import.meta.dirname, "..");
const WEB_DIR = join(ROOT, "web");
const QRCODE_OUT = join(WEB_DIR, "qrcode.bundle.mjs");
const JSQR_OUT = join(WEB_DIR, "jsqr.js");
const JSQR_SOURCE = join(ROOT, "node_modules", "jsqr", "dist", "jsQR.js");

const QRCODE_ENTRY = `
import QRCodeModule from "qrcode/lib/browser.js";
const QRCode = QRCodeModule.default ?? QRCodeModule;
export const create = QRCode.create;
export const toCanvas = QRCode.toCanvas;
export const toDataURL = QRCode.toDataURL;
export const toString = QRCode.toString;
export default QRCode;
`;

async function sameFile(left, right) {
  try {
    const [leftBytes, rightBytes] = await Promise.all([readFile(left), readFile(right)]);
    return Buffer.compare(leftBytes, rightBytes) === 0;
  } catch {
    return false;
  }
}

async function buildQrcodeBundle(outfile) {
  await build({
    stdin: {
      contents: QRCODE_ENTRY,
      resolveDir: ROOT,
      sourcefile: "qrcode-entry.js",
      loader: "js",
    },
    outfile,
    bundle: true,
    format: "esm",
    platform: "browser",
    minify: true,
    legalComments: "none",
    banner: {
      js: "/* Generated by scripts/vendor-qr-libs.mjs from qrcode@1.5.4 (MIT). */",
    },
  });
}

async function buildJsQrBundle(outfile) {
  const source = await readFile(JSQR_SOURCE, "utf8");
  await writeFile(
    outfile,
    `/* Generated by scripts/vendor-qr-libs.mjs from jsqr@1.4.0 (Apache-2.0). */\n${source}`,
  );
}

async function main() {
  if (!CHECK_MODE) {
    await buildQrcodeBundle(QRCODE_OUT);
    await buildJsQrBundle(JSQR_OUT);
    return;
  }

  const tempDir = await mkdtemp(join(tmpdir(), "mazocarta-qr-"));
  try {
    const tempQrcode = join(tempDir, "qrcode.bundle.mjs");
    const tempJsQr = join(tempDir, "jsqr.js");
    await buildQrcodeBundle(tempQrcode);
    await buildJsQrBundle(tempJsQr);
    const [qrcodeMatches, jsQrMatches] = await Promise.all([
      sameFile(QRCODE_OUT, tempQrcode),
      sameFile(JSQR_OUT, tempJsQr),
    ]);
    if (!qrcodeMatches || !jsQrMatches) {
      throw new Error("Vendored QR files are stale. Run `npm run vendor:qr`.");
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
